create  table Person (
    id int generated by default as identity primary key,
    name varchar(20) not null,
    lastname varchar(30) not null,
    email varchar(75) not null,
    date_of_birth date,
    creation_time timestamp

);

create table book
(
    id integer generated by default as identity primary key,
    title varchar(100) not null,
    author varchar(100) not null,
    year integer,
    person_id integer references person on delete set null
)


